### ISSUE TITLE
Add tokenizer

### ISSUE THREAD

**Issue by trutzig89182** [thomjur/PyCollocation#3]
Writing the unit tests I saw that punctuation signs are considered to be part of the words in our first very rough separation of words with word_list = document.split(" ").

So implementing the a tokenizer is an important next step. You already mentioned the NLTK tokenizer in the script.

**Comment by thomjur** [comment]
I agree! I will do that later today. Idea: Add parameter to indicate whether we are dealing with tweets or normal texts in order to switch between `Tokenizer()` and `TweetTokenizer()`.

- [ ] Implement Tokenizer.

**Comment by thomjur** [comment]
I have just implemented a simple tokenizer that also allows to tokenize tweets if needed. Default is the normal `nltk.tokenize.word_tokenize`. It is important to install required nltk packages first (see `README.md`).

**Comment by thomjur** [comment]
Seems to be okay for the moment.
